<!DOCTYPE html SYSTEM "about:legacy-compat"><html lang="en-US" class="win-eval-desktop-val"><!-- Engine version 5.38.880.0--><head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Site map for http://localhost:99/supermarketv3/default.aspx</title><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><meta name="sortsite-ignorerule-page" content="BugHtmlSvg"><meta name="description" content="Site map showing location of issues on http://localhost:99/supermarketv3/default.aspx"><link rel="icon" href="https://www-powermapper-com.azureedge.net/favicon.ico"><link rel="stylesheet" href="Report/report-min-20200618.css"><!--[if lte IE 8]>
            <style type="text/css">
                tr.disabled td img { filter: alpha(opacity=30); }
                div#svgGraph { display:none; }
            </style>
            <![endif]--><!--[if lte IE 7]>
            <style type="text/css">
                div#header { height: 38px; }
                div.subnav { height: 38px; }
            </style>
            <![endif]--><script src="Report/report-min-20191223.js"></script></head><body class="report" id="sitemap"><p class="accessible"><a href="#content">[Skip navigation links]</a></p><noscript><p><strong>Warning:</strong>
                    This report will not work correctly when JavaScript is disabled in your browser.
                </p></noscript><form id="form" action="#"><div><input type="hidden" id="expandedRuleList"><div id="header"><ul><li class="selected"><a id="menu-summary" href="map.htm">Summary</a></li><li><a id="menu-issues" href="map.ERR.htm">Issues</a></li><li><a id="menu-all" href="map.INV.htm">Pages</a></li><li id="menu-page-link"><a rel="nofollow" href="http://localhost:99/supermarketv3/default.aspx">http://localhost:99/supermarketv3/default.aspx</a></li></ul></div><div id="tab-summary"><div class="subnav"><ul><li id="menu-summary-dashboard"><a href="map.htm">Dashboard</a></li><li id="menu-summary-sitemap" class="selected"><a href="#">Site Map</a></li><li id="menu-summary-rules"><a href="map.RUL.htm">What was Tested</a></li></ul></div><main id="content"><h1 class="accessible">Site Report</h1><p class="description">
		This tab shows where errors occur on a map of the site. Each page is represented by a 
		tower, with the widest towers one click from the home page and towers getting narrower
		the more clicks a page is from the home page. The tallest towers indicate pages with most errors.
		Hover over the tops of the towers to see page details. 
	</p><!--POWERMAPPER MAP--></main></div></div></form></body></html>